name: 'capstone'
version: '1.0.0'
config-version: 2

profile: 'capstone'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

vars:
  'raw_database': 'RAW'
  'cap_database': 'CAP_DB'
  'warehouse': 'CAP_WH'


models:
  capstone:
    materialized: table
    staging:
      materialized: view
      +tags: ['staging']
      +database: 'CAP_DB'
    metrics:
      materialized: incremental
      +tags: ['metrics', 'incremental']
      +snowflake_warehouse: 'CAP_WH'
 
tests:
  capstone:
    metrics:
      chw_activity_monthly:
        +severity: warn
