SELECT *
FROM {{ ref('chw_activity_monthly') }}
WHERE TOTAL_ACTIVITIES < 0
   OR UNIQUE_HOUSEHOLDS_VISITED < 0
   OR UNIQUE_PATIENTS_SERVED < 0
   OR PREGNANCY_VISITS < 0
   OR CHILD_ASSESSMENTS < 0
   OR FAMILY_PLANNING_VISITS < 0